name: Update README.md
on:
  schedule:
    # execute every 5 mins
    - cron: '*/5 * * * *'

jobs:
  execute:
    name: Generate modified README.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Installs NodeJS
        uses: actions/setup-node@v2
        with:
          node-verson: '12'

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Modifies readme file
        env:
          REPO: ${{ github.repository }}
        run: |
          npm i
          npm run update_readme

      - if: (success())
        name: Commit changes
        run: |
          git commit -m "Auto updated readme file" -a

      - if: (success())
        name: Pushes commit with update to repo
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: ${{ github.ref }}
